import { defineConfig, type OxfmtConfig } from 'oxfmt';
import baseJson from '../../packages/configs/oxfmt.base.json' with { type: 'json' };

// JSON imports widen literals to `string`, so assert the shape explicitly.
const base: OxfmtConfig = baseJson as OxfmtConfig;

export default defineConfig({
  ...base,
  // Generated by TanStack Router — never format it.
  ignorePatterns: [...(base.ignorePatterns ?? []), '**/routeTree.gen.ts'],
});
