/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedLibraryAgentsIndexRouteImport } from './routes/_authenticated/library/agents/index'
import { Route as AuthenticatedLibraryAgentsAgentIdRouteImport } from './routes/_authenticated/library/agents/$agentId'
import { Route as AuthenticatedLibrarySkillsIndexRouteImport } from './routes/_authenticated/library/skills/index'
import { Route as AuthenticatedLibrarySkillsSkillIdRouteImport } from './routes/_authenticated/library/skills/$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryAgentsIndexRoute =
  AuthenticatedLibraryAgentsIndexRouteImport.update({
    id: '/library/agents/',
    path: '/library/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryAgentsAgentIdRoute =
  AuthenticatedLibraryAgentsAgentIdRouteImport.update({
    id: '/library/agents/$agentId',
    path: '/library/agents/$agentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibrarySkillsIndexRoute =
  AuthenticatedLibrarySkillsIndexRouteImport.update({
    id: '/library/skills/',
    path: '/library/skills/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibrarySkillsSkillIdRoute =
  AuthenticatedLibrarySkillsSkillIdRouteImport.update({
    id: '/library/skills/$skillId',
    path: '/library/skills/$skillId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library/agents/$agentId': typeof AuthenticatedLibraryAgentsAgentIdRoute
  '/library/skills/$skillId': typeof AuthenticatedLibrarySkillsSkillIdRoute
  '/library/agents/': typeof AuthenticatedLibraryAgentsIndexRoute
  '/library/skills/': typeof AuthenticatedLibrarySkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library/agents/$agentId': typeof AuthenticatedLibraryAgentsAgentIdRoute
  '/library/skills/$skillId': typeof AuthenticatedLibrarySkillsSkillIdRoute
  '/library/agents': typeof AuthenticatedLibraryAgentsIndexRoute
  '/library/skills': typeof AuthenticatedLibrarySkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/library/agents/$agentId': typeof AuthenticatedLibraryAgentsAgentIdRoute
  '/_authenticated/library/skills/$skillId': typeof AuthenticatedLibrarySkillsSkillIdRoute
  '/_authenticated/library/agents/': typeof AuthenticatedLibraryAgentsIndexRoute
  '/_authenticated/library/skills/': typeof AuthenticatedLibrarySkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/api/auth/$'
    | '/library/agents/$agentId'
    | '/library/skills/$skillId'
    | '/library/agents/'
    | '/library/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/api/auth/$'
    | '/library/agents/$agentId'
    | '/library/skills/$skillId'
    | '/library/agents'
    | '/library/skills'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/api/auth/$'
    | '/_authenticated/library/agents/$agentId'
    | '/_authenticated/library/skills/$skillId'
    | '/_authenticated/library/agents/'
    | '/_authenticated/library/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library/agents/': {
      id: '/_authenticated/library/agents/'
      path: '/library/agents'
      fullPath: '/library/agents/'
      preLoaderRoute: typeof AuthenticatedLibraryAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/agents/$agentId': {
      id: '/_authenticated/library/agents/$agentId'
      path: '/library/agents/$agentId'
      fullPath: '/library/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedLibraryAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/skills/': {
      id: '/_authenticated/library/skills/'
      path: '/library/skills'
      fullPath: '/library/skills/'
      preLoaderRoute: typeof AuthenticatedLibrarySkillsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/skills/$skillId': {
      id: '/_authenticated/library/skills/$skillId'
      path: '/library/skills/$skillId'
      fullPath: '/library/skills/$skillId'
      preLoaderRoute: typeof AuthenticatedLibrarySkillsSkillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedLibraryAgentsAgentIdRoute: typeof AuthenticatedLibraryAgentsAgentIdRoute
  AuthenticatedLibrarySkillsSkillIdRoute: typeof AuthenticatedLibrarySkillsSkillIdRoute
  AuthenticatedLibraryAgentsIndexRoute: typeof AuthenticatedLibraryAgentsIndexRoute
  AuthenticatedLibrarySkillsIndexRoute: typeof AuthenticatedLibrarySkillsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedLibraryAgentsAgentIdRoute:
    AuthenticatedLibraryAgentsAgentIdRoute,
  AuthenticatedLibrarySkillsSkillIdRoute:
    AuthenticatedLibrarySkillsSkillIdRoute,
  AuthenticatedLibraryAgentsIndexRoute: AuthenticatedLibraryAgentsIndexRoute,
  AuthenticatedLibrarySkillsIndexRoute: AuthenticatedLibrarySkillsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
